package com.bangqu.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bangqu.greendao.entity.DownLoadTask;

import com.bangqu.greendao.dao.DownLoadTaskDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downLoadTaskDaoConfig;

    private final DownLoadTaskDao downLoadTaskDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downLoadTaskDaoConfig = daoConfigMap.get(DownLoadTaskDao.class).clone();
        downLoadTaskDaoConfig.initIdentityScope(type);

        downLoadTaskDao = new DownLoadTaskDao(downLoadTaskDaoConfig, this);

        registerDao(DownLoadTask.class, downLoadTaskDao);
    }
    
    public void clear() {
        downLoadTaskDaoConfig.clearIdentityScope();
    }

    public DownLoadTaskDao getDownLoadTaskDao() {
        return downLoadTaskDao;
    }

}
